# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c5ffb377d42fd736ba765502dbddff4f98d5111542d4483e9b53fffff321b54dd4c138f46d7adda9e1fd72d0247a23a7c3f8620666e807973bb2462cf1fb2163

test:
  secret_key_base: ff3b3002ed0888959f2e50fd3a28bed4125a186ccc6f6feb2f52a93809956dbdcbe9aab023e658718853d8220d428cc99defb1cc8d3e1a4b979cd9dbefa02e60

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
